name: Publish Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore Bank/Bank.sln
    
    - name: Build solution
      run: dotnet build Bank/Bank.sln --configuration Release --no-restore
    
    - name: Install DocFX using .NET Tool
      run: |
        dotnet tool install -g docfx
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
    - name: Generate DocFX metadata
      run: |
        cd Bank
        docfx metadata docfx.json
    
    - name: Build DocFX site
      run: |
        cd Bank
        docfx build docfx.json
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Bank/_site
        cname: # Opcional: agregar tu dominio personalizado aquí
